export const devicesTypes = {
    DEVICES_REQUEST: 'DEVICES_REQUEST',
    DEVICES_UPDATE_REQUEST: 'DEVICES_UPDATE_REQUEST',
    DEVICES_SUCCESS: 'DEVICES_SUCCESS',
    DEVICES_FAILURE: 'DEVICES_FAILURE',
    DEVICES_SUCCESS_ID: 'DEVICES_SUCCESS_ID'
};