export const muteUnmuteNotificationsTypes = {
    MUTE_UNMUTE_NOTIFICATIONS_REQUEST_ID: "MUTE_UNMUTE_NOTIFICATIONS_REQUEST_ID",
    MUTE_UNMUTE_NOTIFICATIONS_SUCCESS: 'MUTE_UNMUTE_NOTIFICATIONS_SUCCESS',
    MUTE_UNMUTE_NOTIFICATIONS_FAILURE: 'MUTE_UNMUTE_NOTIFICATIONS_FAILURE',
};
