export const notificationsTypes = {
    NOTIFICATIONS_REQUEST: "NOTIFICATIONS_REQUEST",
    NOTIFICATIONS_REQUEST_ID: "NOTIFICATIONS_REQUEST_ID",
    NOTIFICATIONS_SUCCESS: 'NOTIFICATIONS_SUCCESS',
    NOTIFICATIONS_FAILURE: 'NOTIFICATIONS_FAILURE',

    NOTIFICATIONS_COUNT: 'NOTIFICATIONS_COUNT',
    NEW_NOTIFICATIONS: 'NEW_NOTIFICATIONS'
};
