export const documentTasksTypes = {
  DOCUMENT_TASKS_REQUEST: "DOCUMENT_TASKS_REQUEST",
  DOCUMENT_TASKS_SUCCESS: "DOCUMENT_TASKS_SUCCESS",
  DOCUMENT_TASKS_FAILURE: "DOCUMENT_TASKS_FAILURE",
  DOCUMENT_TASKS_COUNT: "DOCUMENT_TASKS_COUNT",
  DOCUMENT_TASKS_RESET: "DOCUMENT_TASKS_RESET",
  DOCUMENT__TASK_DRAFTS_INVOICE_INCREMENT: "DOCUMENT__TASK_DRAFTS_INVOICE_INCREMENT",
  DOCUMENT__TASK_DRAFTS_INVOICE_DECREMENT: "DOCUMENT__TASK_DRAFTS_INVOICE_DECREMENT",
  DOCUMENT__TASK_IOS_CAMERA_START: "DOCUMENT__TASK_IOS_CAMERA_START",
   DOCUMENT__TASK_IOS_CAMERA_END: "DOCUMENT__TASK_IOS_CAMERA_END"
};
