export const chatTypes = {
    ADD_PROFILE_IMAGE_REQUEST: "ADD_PROFILE_IMAGE_REQUEST",
    ADD_PROFILE_IMAGE_SUCCESS: "ADD_PROFILE_IMAGE_SUCCESS",
    ADD_PROFILE_IMAGE_FAILURE: "ADD_PROFILE_IMAGE_FAILURE",
    CLEAR_CHAT_STATE: "CLEAR_CHAT_STATE",
    SET_UNREAD_COUNT: "SET_UNREAD_COUNT",
    UPDATE_UNREAD_COUNT: "UPDATE_UNREAD_COUNT",
    RESET_UNREAD_COUNT: "RESET_UNREAD_COUNT"
}
