export const timeTracksTypes = {
    TIMETRACKS_REQUEST: 'TIMETRACKS_REQUEST',
    TIMETRACKS_SUCCESS: 'TIMETRACKS_SUCCESS',
    TIMETRACKS_FAILURE: 'TIMETRACKS_FAILURE',
    IS_TIMETRACKS_SUCCESS: 'IS_TIMETRACKS_SUCCESS',
    IS_CHARGING_PER_HOUR_SUCCESS: 'IS_CHARGING_PER_HOUR_SUCCESS'
};
