export const moneyTrackerTypes = {
  MONEYTRACKER_REQUEST: "MONEYTRACKER_REQUEST",
  MONEYTRACKER_SUCCESS: "MONEYTRACKER_SUCCESS",
  MONEYTRACKER_FAILURE: "MONEYTRACKER_FAILURE",
  MONEYTRACKER_COUNT: "MONEYTRACKER_COUNT",
  MONEYTRACKER_SAVE_MAIN_CURRENCY: "MONEYTRACKER_SAVE_MAIN_CURRENCY",
  MONEYTRACKER_CLEAR_DATA: "MONEYTRACKER_CLEAR_DATA",
  MONEYTRACKER_INVOICES_PRICE: "MONEYTRACKER_INVOICES_PRICE",
  MONEYTRACKER_INVOICES_SAVE_PAYLOAD: "MONEYTRACKER_INVOICES_SAVE_PAYLOAD",
  MONEYTRACKER_SHOW_SUCCESS_SCANNER_MSG:
    "MONEYTRACKER_SHOW_SUCCESS_SCANNER_MSG",
  MONEYTRACKER_IS_LOADING_START: "MONEYTRACKER_IS_LOADING_START",
  MONEYTRACKER_IS_LOADING_END: "MONEYTRACKER_IS_LOADING_END",
};
