export const commentTypes = {
    COMMENT_POST_REQUEST: 'COMMENT_POST_REQUEST',
    COMMENT_DELETE_ALL_REQUEST: 'COMMENT_DELETE_ALL_REQUEST',
    COMMENT_DELETE_REQUEST: 'COMMENT_DELETE_REQUEST',
    COMMENT_SUCCESS: 'COMMENT_SUCCESS',
    COMMENT_FAILURE: 'COMMENT_FAILURE',
    COMMENT_COUNT: 'COMMENT_COUNT',
};
