export const documentsTypes = {
    DOCUMENT_REQUEST: 'DOCUMENT_REQUEST',
    DOCUMENT_SUCCESS: 'DOCUMENT_SUCCESS',
    DOCUMENT_FAILURE: 'DOCUMENT_FAILURE',
    DOCUMENT_COUNT: ' DOCUMENT_COUNT',
    DOCUMENT_SATISTIC: 'DOCUMENT_SATISTIC',
};
