export const projectsTypes = {
    GET_PROJECT_DATA_REQUEST: 'GET_PROJECT_DATA_REQUEST',
    GET_PROJECT_DATA: 'GET_PROJECT_DATA',
    GET_PROJECT_DATA_FAILURE: 'GET_PROJECT_DATA_FAILURE',

    PROJECT_REQUEST: 'PROJECT_REQUEST',
    PROJECT_SUCCESS: 'PROJECT_SUCCESS',
    PROJECT_FAILURE: 'PROJECT_FAILURE',
    PROJECT_COUNT: 'PROJECT_COUNT',
    ID_ROOT_PROJECT: 'ID_ROOT_PROJECT',

    PROJECT_FAVORITE_REQUEST: 'PROJECT_FAVORITE_REQUEST',
    PROJECT_FAVORITE_SUCCESS: 'PROJECT_FAVORITE_SUCCESS',
    PROJECT_FAVORITE_FAILURE: 'PROJECT_FAVORITE_FAILURE',
};
