export const userAuthTypes = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    TOKEN_LOGIN_SUCCESS: 'TOKEN_LOGIN_SUCCESS',
    TOKEN_REFRESH_REQUEST: 'TOKEN_REFRESH_REQUEST',
    STOP_TOKEN_REFRESH_REQUEST: 'STOP_TOKEN_REFRESH_REQUEST',
    TOKEN_REFRESH_SUCCESS: 'TOKEN_REFRESH_SUCCESS',

    USER_DATA_REQUEST: 'USER_DATA_REQUEST',
    USER_DATA_SUCCESS: 'USER_DATA_SUCCESS',
    USER_DATA_FAILURE: 'USER_DATA_FAILURE',
    USER_DATA_ROLE_SUCCESS: 'USER_DATA_ROLE_SUCCESS',

    FORGOT_PASSWORD_REQUEST: 'UFORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
    REMEMBER_LOGIN: 'REMEMBER_LOGIN',
    NOT_REMEMBER_LOGIN: 'NOT_REMEMBER_LOGIN',

    USER_DATA_MODULE_SUCCESS: 'USER_DATA_MODULE_SUCCESS',
    USER_DATA_MODULE_FAILURE: 'USER_DATA_MODULE_FAILURE',
};
